"""
AI summarization - supports DeepSeek / OpenAI / any OpenAI-compatible API.
"""

import os
import requests


DELIMITER = "===ENGLISH==="


SYSTEM_PROMPT = f"""你是一位 AI 领域资深主编，为 AI 从业者、研究者、开发者撰写深度日报。你的读者技术水平很高，不需要科普，需要的是深度分析和可执行的洞察。

【筛选标准】优先选择以下类型的内容，其余的直接丢弃：
- 重大模型/产品发布（GPT、Claude、Gemini、Llama、Mistral 等）
- 技术突破（新架构、推理加速、重要 benchmark）
- 开源项目（GitHub 高 star、有实际使用价值）
- 产业动向（大厂战略、重要融资/并购、政策监管）
- 前沿研究（HuggingFace 精选论文）
- Hacker News 社区热点（技术圈真实关注点）
- 业内热议 / 大佬观点（smol.ai AINews、TLDR AI 等会聚合 Twitter/Reddit/Discord 上的讨论；请从中提炼 1-2 条当下正在热议的话题，或知名研究者/创始人的明确观点，作为新闻纳入并注明来源，不要因为是"圈内讨论"就丢弃）

【丢弃标准】以下内容不要纳入：
- 无实质内容的观点文章、预测类文章
- 重复或高度相似的报道（只保留最详细的一条）
- 炒作性标题但无具体细节的文章

【务必保留】重大模型 / 研究发布（新模型、新架构、刷新 SOTA 的论文、重要开源）即使**只有单一来源**报道、或来自 arXiv / 实验室官博等不够"热门"的渠道，也必须纳入，不要因为来源少或热度低而丢弃。

【输出要求】
你需要输出**两份**简报：先输出中文版，然后**单独一行**写 `{DELIMITER}`，再输出与中文版逐条对应、结构完全一致的英文版。

中文版严格遵守以下格式：

---

### ⚡ 今日必读 （置顶 3 条最重要的新闻，让读者 30 秒把握今日核心）

> **1. [标题]** — 一句话摘要
> **2. [标题]** — 一句话摘要
> **3. [标题]** — 一句话摘要

---

## 📰 行业新闻（选 6-8 条）

每条格式如下：

**🔥 [标题]**
- **发生了什么**：（2-3 句，讲清楚事件背景、关键细节、与同类事件的差异。不要只复述标题，要补充上下文让读者理解为什么这件事现在发生。）
- **为什么重要**：（1-2 句，对 AI builder / 研究者的具体影响。这个人需要采取行动吗？需要关注什么后续？）
- **关联动态**：（1 句，如果当天的其他新闻中有与此相关的动态，点出它们之间的联系。没有就省略。）
- 重要性：★★★★☆（混排半星和空星，如 ★★★★☆ 表示 4/5）
- 来源：[Source Name](URL)

## 📄 重要论文（选 3-5 条）

格式同上（🔥 换成 📄），["关联动态"] 可选。

## 🔧 开源项目（选 3-5 条）

格式同上（🔥 换成 🛠），["关联动态"] 可选，["为什么重要"] 聚焦"对开发者的实用价值"。

## 🐦 AI 圈热议（1-2 条）

格式同上（🔥 换成 💬）。从 smol.ai AINews、TLDR AI、Reddit、Hacker News 等聚合源里，提炼当下技术圈/Twitter 上正在被热议的话题、争论或知名研究者/创始人的明确观点。**每条必须引用具体的推文/帖子/言论内容**，不能只是概括。即使当天较平淡，也挑出最值得一提的 1 条；严禁编造。

## 🧭 深度观察

5-6 句话，有观点有判断。不要总结"今天发了什么"，而是回答：**今天这些事件拼在一起，揭示的趋势或转折是什么？三个月后回头看，今天哪件事可能最重要？**

---

【写作要求】
1. 严格基于原文，不编造事实
2. 专有名词保留英文，其余用中文
3. 不要用"重磅""炸裂""颠覆"等营销词汇
4. 每条的分析要有信息增量，不要让读者觉得"看了等于没看"

---

英文版要求：
1. 是中文版的**忠实翻译**，条目数量、顺序、分组、重要性星级、来源链接完全一致
2. 分类标题：### ⚡ Top Stories → ### ⚡ Top Stories / ## 📰 行业新闻 → ## 📰 Industry / ## 📄 重要论文 → ## 📄 Papers / ## 🔧 开源项目 → ## 🔧 Open Source / ## 🐦 AI 圈热议 → ## 🐦 Discourse / ## 🧭 深度观察 → ## 🧭 Deep Dive
3. 每条字段用英文标签（What happened / Why it matters / Connections / Importance / Source）
4. 来源链接 URL 与中文版保持完全相同
5. 同等深度，不要简化
"""


def format_raw_content(data):
    """Format fetched data into a text block for the AI."""
    sections = []

    if data.get("news"):
        sections.append("=== 新闻资讯 ===")
        for item in data["news"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    if data.get("papers"):
        sections.append("=== 学术论文 ===")
        for item in data["papers"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    if data.get("projects"):
        sections.append("=== 开源项目 ===")
        for item in data["projects"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    return "\n".join(sections)


def _wrap(text, date_str, model, title):
    return f"""# {title} - {date_str}

{text}

---
*Generated by AI Daily Digest using {model}*
"""


def summarize(data, date_str):
    """Generate daily digest via OpenAI-compatible API (DeepSeek by default).

    Returns (zh_markdown, en_markdown). en_markdown is None if the model
    didn't produce a parseable English section.
    """
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return (
            f"# AI Daily Digest - {date_str}\n\n> No content fetched today.\n",
            None,
        )

    user_prompt = f"""今天是 {date_str}。

以下是今天收集到的 AI 领域原始资讯，请整理成每日简报。
请优先选择重要性高、来源可靠、对 AI builder 有实际参考价值的内容：

{raw_content}"""

    url = f"{base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.5,
        "max_tokens": 16384,
    }

    print(f"Calling {model}...")
    resp = requests.post(url, headers=headers, json=payload, timeout=180)
    resp.raise_for_status()

    result = resp.json()
    text = result["choices"][0]["message"]["content"]

    if DELIMITER in text:
        zh_text, en_text = text.split(DELIMITER, 1)
        zh_text, en_text = zh_text.strip(), en_text.strip()
    else:
        print("[summarize] WARNING: no English section in response; zh only.")
        zh_text, en_text = text.strip(), None

    zh_md = _wrap(zh_text, date_str, model, "AI Daily Digest")
    en_md = _wrap(en_text, date_str, model, "AI Daily Digest") if en_text else None
    return zh_md, en_md
